In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    'Gender' : ['M','F','F','M','F','M']
})
df

  Gender
0      M
1      F
2      F
3      M
4      F
5      M

In [2]:
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])
print(df)

   Gender
0       1
1       0
2       0
3       1
4       0
5       1

In [3]:
df1 = pd.DataFrame({
    'City' : ['Pune','Delhi','Mumbai','Banglore']
})
df1

       City
0      Pune
1     Delhi
2    Mumbai
3  Banglore

In [4]:
encode = pd.get_dummies(df1, columns = ['City'], dtype = int)
print(encode)

   City_Banglore  City_Delhi  City_Mumbai  City_Pune
0              0           0            0          1
1              0           1            0          0
2              0           0            1          0
3              1           0            0          0

In [5]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output = False)
result = encoder.fit_transform(df1[['City']])
print(result)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

In [6]:
from sklearn.preprocessing import OrdinalEncoder
df2 = pd.DataFrame({
    'Education':['Graduate','PhD','High School','Post Graduate']
})
df2

       Education
0       Graduate
1            PhD
2    High School
3  Post Graduate

In [7]:
encoder = OrdinalEncoder(categories = [[
    'Graduate','PhD','High School','Post Graduate'
]])
df2['Education'] = encoder.fit_transform(df2[['Education']])
print(df2)

   Education
0        0.0
1        1.0
2        2.0
3        3.0

In [8]:
df3 = pd.DataFrame({
    "City":[
        "Pune",
        "Delhi",
        "Pune",
        "Mumbai",
        "Pune"
    ]
})

df3

     City
0    Pune
1   Delhi
2    Pune
3  Mumbai
4    Pune

In [10]:
frequency = df3["City"].value_counts()

df3["City"] = df3["City"].map(frequency)

print(df3)

   City
0     3
1     2
2     3
3     2
4     3

In [11]:
df4 = pd.DataFrame({
    "City":["Pune","Delhi","Pune","Delhi"],
    "Price":[60,80,55,90]
})

df4

    City  Price
0   Pune     60
1  Delhi     80
2   Pune     55
3  Delhi     90

In [13]:
mean = df4.groupby("City")["Price"].mean()
mean

City
Delhi    85.0
Pune     57.5
Name: Price, dtype: float64

In [14]:
df4['City'] = df4['City'].map(mean)
df4

   City  Price
0  57.5     60
1  85.0     80
2  57.5     55
3  85.0     90