In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
data = {
    'Age': [20,22,30,35,45,56,67,28],
    'Salary': [20000,50000,35000,60000,58000,63000,40000,90000],
    'Purchased': [0,0,0,1,1,1,0,1]
}
df = pd.DataFrame(data)
df

   Age  Salary  Purchased
0   20   20000          0
1   22   50000          0
2   30   35000          0
3   35   60000          1
4   45   58000          1
5   56   63000          1
6   67   40000          0
7   28   90000          1

In [3]:
x = df[['Age','Salary']]
y = df['Purchased']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.3,
    random_state = 42
)

## KNN without scaling

In [5]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.6666666666666666

## Apply StandardScaler

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train_scaled, y_train)
y_pred_scaled = knn.predict(X_test_scaled)
accuracy_score(y_test, y_pred_scaled)

0.3333333333333333

In [8]:
scaled_df = pd.DataFrame(
    X_train_scaled,
    columns = ['Age','Salary']
)
scaled_df

        Age    Salary
0 -0.911076  1.726519
1 -0.770910 -1.116551
2  0.280331  0.072369
3 -0.420496  0.175753
4  1.822151 -0.858090